=== profesorjavi/LLMM/xml_xsd/Pxsd/nivel1/orden.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="orden">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="tipo" type="xs:string"/>
        <xs:element name="objetivo" type="xs:string"/>
        <xs:element name="fuerzas">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="unidad" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="coordenadas">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="latitud" type="xs:decimal"/>
              <xs:element name="longitud" type="xs:decimal"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== profesorjavi/LLMM/xml_xsd/Pxsd/nivel1/orden.xml
<?xml version="1.0" encoding="utf-8"?>
<orden xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="orden.xsd">
  <tipo>ataque</tipo>
  <objetivo>base rebelde Hoth</objetivo>
  <fuerzas>
    <unidad>batallón de AT-AT</unidad>
    <unidad>escuadrón de TIE Fighters</unidad>
  </fuerzas>
  <coordenadas>
    <latitud>-89.123456</latitud>
    <longitud>179.678901</longitud>
  </coordenadas>
</orden>
